Sscs 7937 joint party upload response - WIP
hmcts/sscs-track-your-appeal-notifications pull request #1155
Opened 2020-09-08 15:13 UTC by michaellavelle

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-09-14 08:45 UTC, ryandac requested changes
Evidence reminder changes have somehow made it into your PR, please remove them

2020-09-14 08:45 UTC, ryandac commented on src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
> +                new Object[]{"d994236b-d7c4-44ef-9627-12372bb0434a", Arrays.asList("7d36718b-1193-4b3d-86bd-db54612c5363"), null, null, ORAL, getTemplateName(EVIDENCE_REMINDER_NOTIFICATION, APPELLANT
Has Evidence reminder templates changed?

2020-09-14 08:45 UTC, ryandac commented on src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
> +                new Object[]{"d994236b-d7c4-44ef-9627-12372bb0434a", Arrays.asList("7d36718b-1193-4b3d-86bd-db54612c5363"), null, null, ORAL, getTemplateName(EVIDENCE_REMINDER_NOTIFICATION, APPOINTEE
Is this correct?

2020-09-14 08:45 UTC, ryandac commented on src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
> +                new Object[]{"738b40f4-e7fe-4121-b09d-0a76be4d2fe9", Arrays.asList("00c36e89-6cf0-42a1-b080-6eac4edfca25", "7d36718b-1193-4b3d-86bd-db54612c5363"), null, null, ORAL, getTemplateName(E
Has Evidence Reminder config been added?

2020-09-14 08:45 UTC, ryandac commented on src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
> +                        EVIDENCE_REMINDER_NOTIFICATION,
Better not to add this

2020-09-14 08:45 UTC, ryandac commented on src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
> +                Arrays.asList("7d36718b-1193-4b3d-86bd-db54612c5363"),
Has this changed?

2020-09-14 08:45 UTC, ryandac commented on src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java
> +    private String oralEvidenceReminderJointPartySmsId;
remove evidence Reminder

2020-09-14 08:45 UTC, ryandac commented on src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java
> +            new Object[]{EVIDENCE_REMINDER_NOTIFICATION, ORAL, expectedNumberOfLettersIsZero, isDocmosisLetterFalse}
Remove evidence reminder

2020-09-14 08:45 UTC, ryandac commented on src/e2e/resources/jointParty/oral-evidenceReminderCallback.json
> +{
remove evidence reminder

2020-09-14 08:45 UTC, ryandac commented on src/main/resources/application.yaml
> +          smsId: 7d36718b-1193-4b3d-86bd-db54612c5363
remove evidence reminder changes

2020-09-14 08:45 UTC, ryandac commented on src/main/resources/application.yaml
> +          smsId: 00c36e89-6cf0-42a1-b080-6eac4edfca25
remove evidence reminder changes

2020-09-14 08:45 UTC, ryandac commented on src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
> +    @Parameters({"APPEAL_LAPSED_NOTIFICATION, paper", "APPEAL_LAPSED_NOTIFICATION, oral", "EVIDENCE_REMINDER_NOTIFICATION, oral", "DWP_UPLOAD_RESPONSE_NOTIFICATION, oral"})
remove EVIDENCE_REMINDER_NOTIFICATION, "oral test

2020-09-14 11:34 UTC, ryandac approved these changes

2020-10-09 12:49 UTC, michaellavelle commented
Superseded by https://github.com/hmcts/sscs-track-your-appeal-notifications/pull/1212

2020-10-09 12:49 UTC, closed without merging