SSCS-11390 - Postponement letters that should not be generated
hmcts/sscs-track-your-appeal-notifications pull request #2288
Opened 2023-02-07 16:02 UTC by StevensonSi

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-11390

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-14 09:11 UTC, AndreiTrushkov approved these changes

2023-02-14 17:13 UTC, hajam09 approved these changes

2023-02-14 20:10 UTC, ss-evoco requested changes
This looks to me like you have removed postponement letters entirely. Just checking, we have only removed the GAPS ones yeh ? List Assist ones still work ?

2023-04-26 13:31 UTC, ss-evoco requested changes
You shouldnt be removing the tests, you should be running the inverse of them (checking it doesnt send).

2023-05-04 14:34 UTC, hajam09 approved these changes

2023-05-16 09:14 UTC, merged